-- -----------------------------------------------------
-- Table `SampleModel`
-- -----------------------------------------------------
CREATE TABLE `SampleModel` (
	`id` BIGINT GENERATED BY DEFAULT AS IDENTITY,
	`name` VARCHAR(64) NOT NULL,
	`revision` INTEGER NOT NULL,
	`created` TIMESTAMP NOT NULL,
	`modified` TIMESTAMP NOT NULL
);

INSERT INTO `SampleModel` (`id`, `name`, `created`, `modified`) VALUES (1, 'test1', '2015-11-18T19:42:53.367', '2015-11-18T19:42:53.367');